=== sulad2432603-rishk/prin-143-midterm-activity-03-SULAD-PINGOL-/entertainment.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="https://www.example.com"
    xmlns="https://www.example.com"
    elementFormDefault="qualified">

    <xs:element name="entertainment">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="movie_id" type="xs:string"/>
                <xs:element name="title" type="xs:string"/>
                <xs:element name="release_date">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="year" type="xs:integer"/>
                            <xs:element name="month" type="xs:string"/>
                            <xs:element name="date" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="genre" type="xs:string"/>
                <xs:element name="language" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== sulad2432603-rishk/prin-143-midterm-activity-03-SULAD-PINGOL-/entertainment.xml
<?xml version="1.0" encoding="UTF-8"?>
<entertainment xmlns="https://www.example.com"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="https://www.example.com entertainment.xsd">

    <movie_id>MOV247</movie_id>
    <title>City Of Angels</title>

    <release_date>
        <year>1998</year>
        <month>April</month>
        <date>10</date>
    </release_date>

    <genre>Romance</genre>
    <language>English</language>

</entertainment>
