=== sulad2432603-rishk/prin-143-midterm-activity-03-SULAD-PINGOL-/management.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="https://www.example.com"
    xmlns="https://www.example.com"
    elementFormDefault="qualified">

    <xs:element name="management">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="lastName" type="xs:string"/>
                            <xs:element name="firstName" type="xs:string"/>
                            <xs:element name="middleName" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="age" type="xs:integer"/>
                <xs:element name="DOB">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="year" type="xs:integer"/>
                            <xs:element name="month" type="xs:string"/>
                            <xs:element name="date" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="course" type="xs:string"/>
                <xs:element name="year_section" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== sulad2432603-rishk/prin-143-midterm-activity-03-SULAD-PINGOL-/management.xml
<?xml version="1.0" encoding="UTF-8"?>
<management xmlns="https://www.example.com"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="https://www.example.com management.xsd">

    <name>
        <lastName>Sulad</lastName>
        <firstName>Irish</firstName>
        <middleName>Frisnedi</middleName>
    </name>
    <age>19</age>
    <DOB>
        <year>2006</year>
        <month>May</month>
        <date>27</date>
    </DOB>
    <course>Information Technology</course>
    <year_section>2-A</year_section>

</management>
