=== sulad2432603-rishk/prin-143-midterm-activity-03-SULAD-PINGOL-/retail.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="https://www.example.com"
    xmlns="https://www.example.com"
    elementFormDefault="qualified">

    <xs:element name="retail">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="price" type="xs:decimal"/>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="type" type="xs:string"/>
                <xs:element name="dop">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="year" type="xs:integer"/>
                            <xs:element name="month" type="xs:string"/>
                            <xs:element name="date" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="exp">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="year" type="xs:integer"/>
                            <xs:element name="month" type="xs:string"/>
                            <xs:element name="date" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== sulad2432603-rishk/prin-143-midterm-activity-03-SULAD-PINGOL-/retail.xml
<?xml version="1.0" encoding="UTF-8"?>
<retail xmlns="https://www.example.com"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="https://www.example.com retail.xsd">

    <price>200.00</price>
    <name>Liquid Lipstick</name>
    <type>Cosmetics</type>
    <dop>
        <year>2026</year>
        <month>April</month>
        <date>15</date>
    </dop>
    <exp>
        <year>2027</year>
        <month>April</month>
        <date>15</date>
    </exp>

</retail>
