=== sulad2432603-rishk/prin-143-midterm-activity-03-SULAD-PINGOL-/services.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="https://www.example.com"
    xmlns="https://www.example.com"
    elementFormDefault="qualified">

    <xs:element name="services">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="lastName" type="xs:string"/>
                            <xs:element name="firstName" type="xs:string"/>
                            <xs:element name="middleName" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="age">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="25"/>
                            <xs:maxInclusive value="55"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="nationality" type="xs:string"/>
                <xs:element name="partylist" type="xs:string"/>
                <xs:element name="number" type="xs:integer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== sulad2432603-rishk/prin-143-midterm-activity-03-SULAD-PINGOL-/services.xml
<?xml version="1.0" encoding="UTF-8"?>
<services xmlns="https://www.example.com"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="https://www.example.com services.xsd">

    <name>
        <lastName>Sulad</lastName>
        <firstName>Kristel</firstName>
        <middleName>Frisnedi</middleName>
    </name>
    <age>45</age>
    <nationality>Filipino</nationality>
    <partylist>CommunityCare</partylist>
    <number>072707</number>

</services>
